### PR TITLE
Like working

### PR DESCRIPTION
**Pull request by jgescobar**

### CODE REVIEW

**Comment by jgescobar** [comment]
like is re rendered when clicked on to show single image with updated likes

**Comment by h4w5** [comment]
Awesome, I'll take a look tomorrow! Addresses #5.

**Comment by jgescobar** [comment]
ok thank you. Ill pull the updated code tomorrow then.
Thank you !

**Comment by h4w5** [comment]
Looks good! Happy Easter! :rabbit2: :tulip:

**Comment by jgescobar** [comment]
Thanks Phil! Happy Easter to you and your wife as well :)

**Pull request merged**
