### PR TITLE
turned show on in api_routes.js

### PR DESCRIPTION
**Pull request by jgescobar**

### CODE REVIEW

**Comment by h4w5** [comment]
Looks good! I'll check it in the AM. FYI the other issues are up now.

**Comment by h4w5** [comment]
#1.

**Comment by h4w5** [comment]
@jgescobar 

Received this error:



1. The response text in the error is saying "Id is not defined... My guess is that there is something wrong with [this line](https://github.com/h4w5/wdinstagram_collaboration_challenge/pull/7/files#diff-18d1119174046d9ca6b6144399031b80R16). Make sure that you are grabbing the `id` from the request! (`req`).
2. When you get an error that you can't find an id, I want it to return a status code `404`, not `500`! **`500 (Internal Server Error)`** should almost NEVER be your response. :) Check it out [here](http://expressjs.com/en/api.html#res.sendStatus).

I'll close. Resubmit and open!

**Comment by jgescobar** [comment]
AAU I want the show function to work. 

New Error I get 
https://i.imgur.com/GBQgXAj.png

Function I re-wrote where I got this new error
https://i.imgur.com/89m1Z0r.png

Im not getting any localhost issues now, im getting jquery and lodash template issues. Where could i fix this?

**Pull request closed without merging**
